import = [ "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml" ]

[env]
TERM="xterm-256color"

[window]
dimensions.columns = 110
dimensions.lines = 38
padding.x=8
padding.y=8
dynamic_padding = true
# opacity = 0.9
# blur = true

decorations = "Buttonless"

option_as_alt ="Both"

[font]
normal.family = "ZedMono Nerd Font Mono"
normal.style = "Extended"
size =16
offset.x = 0
offset.y = 3
