# [Alacritty Theme](https://github.com/alacritty/alacritty-theme/tree/master)

import = [ "~/.config/alacritty/themes/catppuccin_macchiato.toml" ]

[env]
TERM="xterm-256color"

[window]
dimensions.columns = 110
dimensions.lines = 38
padding.x=4
padding.y=7
dynamic_padding = true
decorations = "Buttonless"
option_as_alt ="Both"

[font]
normal.family = "ZedMono Nerd Font Mono"
normal.style = "Extended"
size =15
offset.x = 0
offset.y = 2
