# ~/.tmuxinator/work.yml
name: project
root: /Users/akc/OneDrive/Projects #<%= @args[0] %>

windows:
  - code:
      layout: main-vertical
      panes:
  - term:
      layout: main-vertical
      panes:
