-- Monitor layout (was sway/outputs, generated by nwg-displays — now hand-edited;
-- nwg-displays writes hyprlang, not Lua, so it's retired).
--
-- Positions are in logical (scaled) pixels: HDMI-A-1 is 3840x2160/1.6 =
-- 2400x1350 with eDP-1 directly below it, 222px in from the HDMI's left edge
-- (same relative placement the sway layout had).
--
-- Exported as a module so displays.lua can re-apply the canonical layout to
-- undo runtime mirror/disable states.

local M = {}

M.INTERNAL = "eDP-1" -- built-in panel; every other output is "external"

M.MONITORS = {
    { output = "HDMI-A-1", mode = "3840x2160@30",     position = "0x0",      scale = 1.6 },
    { output = "eDP-1",    mode = "1920x1200@60.003", position = "222x1350", scale = 1.0 },
    -- Fallback for any monitor not listed above.
    { output = "",         mode = "preferred",        position = "auto",     scale = 1.0 },
}

-- Re-apply the configured rule for one output (fallback rule if unknown).
function M.apply(name)
    for _, m in ipairs(M.MONITORS) do
        if m.output == name then
            hl.monitor(m)
            return
        end
    end
    hl.monitor({ output = name, mode = "preferred", position = "auto", scale = 1.0 })
end

-- Re-apply the whole canonical layout (undoes mirror/disabled states).
function M.apply_all()
    for _, m in ipairs(M.MONITORS) do
        hl.monitor(m)
    end
end

M.apply_all()

return M
