# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

settings=$HOME/Dropbox/dotfiles/shell

source ${settings}/alias.sh
source ${settings}/functions.sh
source ${settings}/tmux_functions.sh
source ${settings}/git_functions.sh
source ${settings}/apps.sh
source ${settings}/lazy.theme.sh

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
#paths to directory's
export DOT="/Users/lazy/Dropbox/dotfiles/"
export QE="/Users/lazy/Dropbox/Espresso/"
export SISSA="/Users/lazy/Dropbox/School/SISSA"
# added by Anaconda3 installer
export PATH="/Users/lazy/anaconda3/bin:$PATH"

# ZSH_THEME="robbyrussell"
ZSH_THEME="lazy"
# DISABLE_AUTO_UPDATE="true"
# ENABLE_CORRECTION="true"
# ZSH_CUSTOM=/path/to/new-custom-folder
PATH="/usr/local/bin:/Users/lazy/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin"

plugins=(
  # tmux
  zsh-syntax-highlighting
  # zsh-autosuggestions
  osx
  colored-man-pages
  marked2
)

source $ZSH/oh-my-zsh.sh

# User configuration
