# activating bashrc if found
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

# export PATH="/usr/local/Cellar/gcc/6.3.0_1/bin:$PATH"
export PATH="/usr/local/bin:$PATH"

# added by Anaconda3 4.3.0 installer
export PATH="/Users/lazy/conda3/bin:$PATH"
